# EVENTS

### Get all events
GET http://localhost:7005/events HTTP/1.1

### Get single event
GET http://localhost:7005/events/150e4b0a-5a53-43a3-8e18-97e67065ea92 HTTP/1.1

### Not Found
GET http://localhost:7005/events/11111111-2222-3333-4444-555555555555 HTTP/1.1

### Create event
POST http://localhost:7005/events HTTP/1.1
Content-Type: application/json

{
  "name": "REST-event-w-requirements-wo-description",
  "requirements": [
    { "name": "video" },
    { "name": "cooking" },
    { "name": "driving" }
  ]
}

### Delete event
DELETE http://localhost:7005/events/c9f6305e-2ae1-41aa-9b1a-da651c2417fb HTTP/1.1

### Add participant to event
POST http://localhost:7005/events/150e4b0a-5a53-43a3-8e18-97e67065ea92/participants HTTP/1.1
Content-Type: application/json

{
  "_id": "8478fc36-5bbb-410a-bc0f-20fe1e4daf3d",
  "name": "WEB Filtrovic",
  "dispositions": [
    "video",
    "cooking"
  ]
}

### Add fullfillment for participant
PUT http://localhost:7005/events/150e4b0a-5a53-43a3-8e18-97e67065ea92/fullfill HTTP/1.1
Content-Type: application/json

{
  "user_id": "8478fc36-5bbb-410a-bc0f-20fe1e4daf3d",
  "user_name": "WEB Filtrovic",
  "requirement_name": "video"
}

### Remove fullfillment for participant
PUT http://localhost:7005/events/150e4b0a-5a53-43a3-8e18-97e67065ea92/unfullfill HTTP/1.1
Content-Type: application/json

{
  "user_id": "8478fc36-5bbb-410a-bc0f-20fe1e4daf3d",
  "requirement_name": "video"
}

### Remove participant from event
DELETE http://localhost:7005/events/150e4b0a-5a53-43a3-8e18-97e67065ea92/participants/8478fc36-5bbb-410a-bc0f-20fe1e4daf3d HTTP/1.1

# USERS

### Get all users
GET http://localhost:7005/users HTTP/1.1

### Get single user
GET http://localhost:7005/users/0ab8c67b-34ab-48c9-9ade-0da5975ea8ab HTTP/1.1

### Not Found
GET http://localhost:7005/users/11111111-2222-3333-4444-555555555555 HTTP/1.1

### Update user
PUT http://localhost:7005/users/0ab8c67b-34ab-48c9-9ade-0da5975ea8ab HTTP/1.1
Content-Type: application/json

{
  "name": "REST Janko-Hrasko PUT",
  "dispositions": [
    "cooking",
    "audio",
    "video",
    "driving"
  ]
}

### Create user
POST http://localhost:7005/users HTTP/1.1
Content-Type: application/json

{
  "name": "REST Janko-Hrasko",
  "dispositions": ["cooking", "audio", "video", "driving"]
}

### Delete user
DELETE http://localhost:7005/events/0ab8c67b-34ab-48c9-9ade-0da5975ea8ab HTTP/1.1


# REFERENCE DATA

###
GET http://localhost:7005/ref_data HTTP/1.1

###
GET http://localhost:7005/ref_data/all HTTP/1.1